name: CI/CD with Approval

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  deploy-to-production:
    needs: test-and-lint
    runs-on: ubuntu-latest
    environment:
      name: production
      # GitHub will pause here and wait for manual approval
    steps:
      - name: Deploying to production
        run: echo "Deploying to production..."
